docker save -o msconsul_order.tgz msconsul_order
docker save -o msconsul_hystrix-dashboard.tgz msconsul_hystrix-dashboard
docker save -o msconsul_apache.tgz msconsul_apache
docker save -o msconsul_catalog.tgz msconsul_catalog
docker save -o msconsul_customer.tgz msconsul_customer
docker save -o alpine.tgz alpine
docker save -o consul.tgz consul
docker save -o ubuntu.tgz ubuntu
docker save -o java.tgz ewolff/docker-java
docker save -o filebeat.tgz docker.elastic.co/beats/filebeat
docker save -o elasticsearch.tgz docker.elastic.co/elasticsearch/elasticsearch
docker save -o kibana.tgz docker.elastic.co/kibana/kibana 
docker save -o prometheus.tgz prom/prometheus    
