docker save -o loganalysis_kibana.tgz loganalysis_kibana
docker save -o loganalysis_user-registration.tgz loganalysis_user-registration
docker save -o loganalysis_logstash.tgz loganalysis_logstash
docker save -o loganalysis_elasticsearch.tgz loganalysis_elasticsearch
docker save -o graphite_graphite-web.tgz graphite_graphite-web
docker save -o graphite_user-registration.tgz graphite_user-registration
docker save -o graphite_carbon.tgz graphite_carbon
docker save -o msconsul_order.tgz msconsul_order
docker save -o msconsul_hystrix-dashboard.tgz msconsul_hystrix-dashboard
docker save -o msconsul_apache.tgz msconsul_apache
docker save -o msconsul_catalog.tgz msconsul_catalog
docker save -o msconsul_customer.tgz msconsul_customer
docker save -o alpine.tgz alpine
docker save -o consul.tgz consul
docker save -o ubuntu.tgz ubuntu
docker save -o java.tgz ewolff/docker-java